# Generated by Django 2.1.4 on 2019-02-02 16:56

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='data_posted',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 2, 16, 56, 16, 402131, tzinfo=utc)),
        ),
    ]
