# Generated by Django 2.1.4 on 2019-02-02 17:09

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20190202_2226'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='data_posted',
        ),
        migrations.AddField(
            model_name='post',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 2, 17, 9, 53, 358017, tzinfo=utc)),
        ),
    ]
