# Generated by Django 2.1.5 on 2019-02-06 17:32

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20190204_1955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 6, 17, 32, 43, 694539, tzinfo=utc)),
        ),
    ]
